### ISSUE TITLE
VIM gitgutter / other plugins

### ISSUE THREAD

**Issue by btopro** [nateswart/toolbox#2]
anything you have to do to get git gutter to be enabled? I see the line endings change a bit after installing via the directions on the homepage but nothing really else going on in VIM

**Comment by nateswart** [comment]
I did notice that I needed to turn on line numbers (at least, that is what worked for me). I have them in the .vimrc now:

set number
set numberwidth=3

After you :w changes on a version controlled file, you'll see the git gutter marking up your file in the gutter to track your changes.
